name: Deploy website on push
on:
  push:
    branches:
      -'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Sync files
      with:
        server: ftp.stageservices.xyz
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /public_html/maingitactions/